version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_VAPID_PUBLIC_KEY: ${NEXT_PUBLIC_VAPID_PUBLIC_KEY}
        VAPID_CONTACT_EMAIL: ${VAPID_CONTACT_EMAIL}
        VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
        AWS_REGION: ${AWS_REGION}
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "3000:3000"
